name: Same-token Push -> 403 (quarantine)

on: { workflow_dispatch: {} }

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login (same token whole job)
        uses: docker/login-action@v3
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CS_USER }}    # service account slug
          password: ${{ secrets.CS_TOKEN }}   # entitlement (Download+Upload ON)

      - name: Build
        run: |
          echo 'FROM alpine:3.20' > Dockerfile
          echo 'RUN echo hi'     >> Dockerfile
          docker build -t docker.cloudsmith.io/rini-jain-rnye/api_repo/vulnimage:latest .

      - name: Push
        run: |
          docker push docker.cloudsmith.io/rini-jain-rnye/api_repo/vulnimage:latest

      # 👇 Same token; quarantine/policy should block reads now
      - name: HEAD/GET manifest by TAG (expect 403 if quarantined)
        run: |
          set -eux
          BASE="https://docker.cloudsmith.io/v2/rini-jain-rnye/api_repo/vulnimage/manifests"
          # krane-style HEAD then GET
          curl -sS -o /dev/null -w "HEAD=%{http_code}\n" \
            -u "${{ secrets.CS_USER }}:${{ secrets.CS_TOKEN }}" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            "${BASE}/latest" || true
          curl -sS -o /dev/null -w "GET =%{http_code}\n" \
            -u "${{ secrets.CS_USER }}:${{ secrets.CS_TOKEN }}" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            "${BASE}/latest" || true

      - name: Pull by TAG (expect 403 if quarantined)
        run: |
          docker pull docker.cloudsmith.io/rini-jain-rnye/api_repo/vulnimage:latest || true
