name: Cloudsmith Push & Get Digest (Simple)

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Cloudsmith
        uses: docker/login-action@v3
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CS_USER }}   # service account slug
          password: ${{ secrets.CS_TOKEN }}  # entitlement token (download+upload)

      - name: Build image
        run: |
          docker build -t docker.cloudsmith.io/rini-jain-rnye/api_repo/vulnimage:latest .

      - name: Push image
        run: |
          docker push docker.cloudsmith.io/rini-jain-rnye/api_repo/vulnimage:latest

      # ✅ No pull needed: get digest directly from registry via HEAD
      - name: Get image digest (HEAD)
        id: digest
        run: |
          MANIFEST_URL="https://docker.cloudsmith.io/v2/rini-jain-rnye/api_repo/vulnimage/manifests/latest"
          DIGEST=$(curl -sI -u "${{ secrets.CS_USER }}:${{ secrets.CS_TOKEN }}" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            "$MANIFEST_URL" | awk -F': ' '/Docker-Content-Digest:/ {gsub(/\r/,"",$2); print $2; exit}')
          echo "Digest: $DIGEST"
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

      # (optional) verify by digest
      - name: Pull by digest (optional)
        if: env.DIGEST != ''
        run: |
          docker pull docker.cloudsmith.io/rini-jain-rnye/api_repo/vulnimage@"$DIGEST"
